### ISSUE TITLE
Create scripts to start several apps simultaneously

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/docs#10]
@arunge waiting on the script options as we discussed

_Originally posted by @isomemo in https://github.com/Pandora-IsoMemo/drat/issues/18#issuecomment-1447973918_

**Comment by arunge** [comment]
### Scripts for docker containers

Currently:
- one can only start one app (via docker) in a terminal
- apps are running even if the terminal is closed
- one can stop apps with a specific docker command (`docker stop <id>` and `docker rm <id>`) using the id for the app (`docker ps`), or by shutting down the computer

Plan: one terminal for all apps

To start several docker containers and use one terminal for all apps: 
- we must start apps running in the background not in the foreground which is currently the case
- we must update the `run docker` commands and name each app
- then one can stop apps with a specific docker command using the name for the app

When running in background, 
- apps will run even if the terminal is closed. We need to stop apps with a specific docker command using the name for the app.
- error messages are not displayed. One must use specific commands to see an error message.

We can prepare scripts that contain basic docker commands 
- to check which apps are running
- for other typical use cases, e.g. 
  - closing all running apps, 
  - opening several apps at the same time
- use “if-else” clauses with options (1:..., 2:...) such that user chooses

Idea:
- check if we can use “Make-Files”

**Comment by isomemo** [comment]
@arunge can one use IF conditions in Docker? If, so why cannot we give a list of apps to the user (e.g., 1 PlotR, 2 BMSC, ...). If the user select 2 a stop command is executed (even if no app is running in the background) and then a command is executed to launch BMSC. In this way, you would not need to run all apps in the background.

**Comment by jan-abel-inwt** [comment]
Hello @isomemo,

I've prepared the initial draft of this bash script. Could you please advise on where it should be made accessible to users?

Including it in the wikis for copying and pasting purposes might not be the most efficient strategy, given the script's length, which exceeds already 100 lines. This could make the process quite burdensome.

As an alternative, I propose creating a new repository, potentially titled `Pandora-IsoMemo-helpers`. This could 
also serve as a future location for similar scripts, such as the Windows version of this script.

What are your thoughts on this?

**Comment by jan-abel-inwt** [comment]
I created a new repository https://github.com/Pandora-IsoMemo/HelperScripts

There you can find the first draft of the script to start several docker container.

**Comment by arunge** [comment]
As discussed, we will update the name of the repository "HelperScripts" to "all-in-one-apps". Blank spaces are not allowed in repository names.

**Comment by arunge** [comment]
For documentation purpose: Scripts are now living in
- https://pandora-isomemo.github.io/docs/scripts.html
- https://github.com/Pandora-IsoMemo/docs/tree/main/scripts
