### ISSUE TITLE
Add Link to Documentation Hub on Old Landing Page

### ISSUE THREAD

**Issue by jan-abel-inwt** [Pandora-IsoMemo/docs#3]
>

**Comment by jan-abel-inwt** [comment]
![image](https://github.com/user-attachments/assets/07a82d37-fa6d-4e1e-81e9-10d40a96ddc2)


@arunge I added this yellow banner at the top of the old landing page.

I also removed the construction banner from the new page and adjusted some elements of the website.

Is there anything else you'd like adjusted?

**Comment by jan-abel-inwt** [comment]
All content (images, texts, etc.) from the old site has been successfully transferred to the new one. The only elements I haven't yet moved over are the logo, the two links, and the copyright information in the footer. Should these be replicated exactly as they are, omitted, or should we make some modifications?

![image](https://github.com/user-attachments/assets/aba2a738-d29b-4c57-9020-8a22b428f9fb)

With this, the old site can also be taken offline. What do you think @isomemo ?

**Comment by arunge** [comment]
@jan-abel-inwt No links, logos, copyright info should be added for now.
